//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::calc_var::Entity as CalcVar;
pub use super::channel::Entity as Channel;
pub use super::message::Entity as Message;
pub use super::user::Entity as User;
